### PR TITLE
lab7

### PR DESCRIPTION
**Pull request by coado**

### CODE REVIEW

**Comment by coado** [comment]
Accept ASAP

**Comment by Eniterusx** [comment]
No

**Comment by Eniterusx** [comment]
Ok actually yes

**Comment by Eniterusx** [comment]
I reviewed the request

**Comment by Eniterusx** [comment]
It was very good

**Comment by Eniterusx** [comment]
I approve it wholeheartedly

**Comment by Eniterusx** [comment]
Keep up the good work!

**Pull request merged**
